# etl_schedule.yml

name: ETL Pipeline Schedule

on:
  schedule:
    - cron: "0 3 * * 1"  # Runs every Monday at 03:00 UTC

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run ETL Pipeline
        run: |
          source venv/bin/activate
          python src/etl/etl_pipeline.py
