name: Weekly ETL
on:
  push:
    branches:
      - sprint-etl-api
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'   # Monday 03:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

       - name: Install deps
  run: npm install --no-audit --no-fundd


      - name: Run ETL script
        run: npx ts-node etl/fetch_nrcan.ts
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
