  name: Weekly ETL
  on:
    push:
      branches:
        - sprint-etl-api
    workflow_dispatch:
    schedule:
      - cron: '0 3 * * 1'   # Monday 03:00 UTC

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx ts-node etl/fetch_nrcan.ts
        env:
          SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
