name: Generate Lockfile
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: |
          git config user.email "actions@github.com"
          git config user.name  "github-actions[bot]"
          git add package-lock.json
          git commit -m "chore: add package-lock.json"
      - run: git push
      - run: |
          git rm .github/workflows/generate-lockfile.yml
          git commit -m "chore: remove lockfile workflow [skip ci]"
          git push
