name: Move project to root
on:
  worispatch: {}
jobs:
  move:
    runs-on: ubuntu-latest
    steps:
  - u  : actions/checkout@v4
        with: { token: ${{ secrets.GITHUB_TOKEN }} }

      - name: Move files
        run: |
          shopt -s dotglob
          mv src/web/* .
          rm -rf src/web
          rm -f vercel.json
          git add .
          git config user.name  "Operator Bot"
          git config user.email "bot@operator.local"
          git commit -m "Move Next.js project to repo root (CI)"
      - run: git push
