name: Move project to repo root
on:
  workflow_dispatch:
jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Next.js files to root
        run: |
          shopt -s dotglob
          mv src/web/* .
          rm -rf src/web vercel.json
          git add .
          git config user.email "bot@operator.local"
          git config user.name  "Operator Bot"
          git commit -m "Move Next.js project to repo root"
          git push
